# -*- coding: utf-8 -*-
"""APP COSTOS FC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14IYdLx44wN1Hu3J8YQQGmXMNQBXz8gJR
"""

!pip install streamlit
!pip install pyngrok

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
from scipy.optimize import minimize
import plotly.express as px
import streamlit as st

st.title ("Simulación de Portafolios - Frontera Eficiente de Markowitz")

#Lista de tickers inicial
lista_tickers= ["GOOG", "AAPL", "BAC"]

#multiselector
tickers = st.multiselect("Elija un ticker", lista_tickers)

#Boton
if st.button("Descargar"):
  data = yf.download(tickers,start="2022-01-01", end="2025-01-01")['Close']
  st.dataframe(data)
else:
    st.warning("Seleccione los tickers y haga clic en 'Descargar datos' para iniciar.")

tickers = ["GOOG", "AAPL", "BAC"]

# Descargamos precios ajustados de los últimos 3 años
data = yf.download(tickers, start="2022-01-01", end="2025-01-01")['Close']

# Mostramos las primeras filas
print("Datos descargados:")
print(data.head(5))

data.tail(5) # Veo los últimos 5 datos

# Calculate daily returns
returns = data.pct_change().dropna()

# Calcular el rendimiento esperado anual
expected_returns = returns.mean() * 252
# Calcular la matriz de covarianza anual
cov_matrix = returns.cov() * 252

print("Expected Returns (Annual):")
print(expected_returns)
print("\nCovariance Matrix (Annual):")
print(cov_matrix)

# Create a DataFrame for annualized returns
df_rendimientos = pd.DataFrame({
    'Ticker': expected_returns.index,
    'Rendimiento Anualizado': expected_returns.values
})

# Crear la gráfica
fig = px.bar(
    df_rendimientos,
    x='Ticker',
    y='Rendimiento Anualizado',
    text='Rendimiento Anualizado',
    title='📈 Rendimiento Anualizado por Activo (2022–2025)',
    labels={'Rendimiento Anualizado': 'Rendimiento (%)'}
)

# Mostrar valores en porcentaje
fig.update_traces(texttemplate='%{text:.2%}', textposition='outside')
fig.update_layout(yaxis_tickformat=".1%", showlegend=False)

fig.show()

num_portfolios = 10000
results = np.zeros((3, num_portfolios))
weights_record = np.zeros((num_portfolios, len(tickers)))

for i in range(num_portfolios):
    weights = np.random.random(len(tickers))
    weights /= np.sum(weights) #normalizamos
    returns, volatility = portfolio_performance(weights, expected_returns, cov_matrix)
    results[0, i] = returns
    results[1, i] = volatility
    results[2, i] = returns / volatility
    weights_record[i, :] = weights

# Convertir resultados a un DataFrame
results_df = pd.DataFrame(results.T, columns=["Rendimiento", "Volatilidad", "Ratio de Sharpe"])
weights_df = pd.DataFrame(weights_record, columns=cov_matrix.columns)

# Concatenar los DataFrames de resultados y pesos
final_df = pd.concat([results_df, weights_df], axis=1)

# Encontrar el portafolio con el mejor Ratio de Sharpe
max_sharpe_idx = results_df["Ratio de Sharpe"].idxmax()
max_sharpe_port = results_df.iloc[max_sharpe_idx]

# Encontrar el portafolio con la mínima volatilidad
min_vol_idx = results_df["Volatilidad"].idxmin()
min_vol_port = results_df.iloc[min_vol_idx]


# Imprimir los pesos de los portafolios óptimos
print("Pesos del portafolio con el mejor Ratio de Sharpe:")
print(weights_df.iloc[max_sharpe_idx])
print("\nPortafolio con el mejor Ratio de Sharpe:")
print(f"Rendimiento Esperado: {max_sharpe_port['Rendimiento']*100:.2f}%")
print(f"Volatilidad: {max_sharpe_port['Volatilidad']*100:.2f}%")
print(f"Ratio de Sharpe: {max_sharpe_port['Ratio de Sharpe']:.2f}")

print("\nPesos del portafolio con la mínima Volatilidad:")
print(weights_df.iloc[min_vol_idx])
print("\nPortafolio con la mínima Volatilidad:")
print(f"Rendimiento Esperado: {min_vol_port['Rendimiento']*100:.2f}%")
print(f"Volatilidad: {min_vol_port['Volatilidad']*100:.2f}%")
print(f"Ratio de Sharpe: {min_vol_port['Ratio de Sharpe']:.2f}")

plt.figure(figsize=(10,7))

# Puntos de todos los portafolios
scatter = plt.scatter(results_df["Volatilidad"], results_df["Rendimiento"],
                      c=results_df["Ratio de Sharpe"], cmap='viridis')
plt.colorbar(scatter, label="Ratio de Sharpe")

# Portafolio de Máximo Sharpe (rojo)
plt.scatter(max_sharpe_port["Volatilidad"], max_sharpe_port["Rendimiento"],
            color='red', marker='*', s=250, label='Máximo Sharpe Ratio')

# Portafolio de Mínima Volatilidad (azul)
plt.scatter(min_vol_port["Volatilidad"], min_vol_port["Rendimiento"],
            color='blue', marker='*', s=250, label='Mínima Volatilidad')

# Títulos y etiquetas
plt.title("Frontera Eficiente de Markowitz", fontsize=14, fontweight='bold')
plt.xlabel("Volatilidad (Riesgo)", fontsize=12)
plt.ylabel("Rendimiento Esperado (%)", fontsize=12)
plt.legend(loc='best', fontsize=11)
plt.grid(True, linestyle='--', alpha=0.6)

plt.show()

"""## Interpretación general

Los puntos amarillos o verde claro son los más deseables (portafolios más eficientes).

Los puntos azul oscuro son los menos convenientes, porque tienen una mala relación riesgo/retorno.

La estrella roja (máximo Sharpe) está en la zona más amarilla, indicando el portafolio más eficiente posible.

La estrella azul (mínima volatilidad) suele estar en una zona más baja o azul, porque prioriza seguridad sobre rendimiento.
"""